plugins {
    id "architectury-plugin" version "3.5-SNAPSHOT"
    id "dev.architectury.loom-no-remap" version "1.14-SNAPSHOT" apply false
}

architectury {
    minecraft = project.minecraft_version
}

allprojects {
    group = rootProject.maven_group
    version = rootProject.mod_version

    repositories {
        maven {
            name = 'NeoForge'
            url 'https://maven.neoforged.net/releases'
        }
        maven {
            name = 'CurseForge'
            url 'https://minecraft.curseforge.com/api/maven'
        }
        maven {
            url = "https://maven.midnightdust.eu/releases"
        }
        maven {
            name = 'TerraformersMC'
            url = 'https://maven.terraformersmc.com/releases'
        }
        mavenLocal()
        mavenCentral()
    }
}

subprojects {
    apply plugin: "dev.architectury.loom-no-remap"
    apply plugin: 'architectury-plugin'

    base {
        archivesName = "$rootProject.archives_name-$project.name"
    }

    loom {
        silentMojangMappingsLicense()
    }

    dependencies {
        minecraft "com.mojang:minecraft:${rootProject.minecraft_version}"
        compileOnly 'org.projectlombok:lombok:1.18.40'
        annotationProcessor 'org.projectlombok:lombok:1.18.40'
        testCompileOnly 'org.projectlombok:lombok:1.18.40'
        testAnnotationProcessor 'org.projectlombok:lombok:1.18.40'
    }

    java {
        withSourcesJar()
        sourceCompatibility = JavaVersion.VERSION_21
        targetCompatibility = JavaVersion.VERSION_21
    }

    tasks.withType(JavaCompile).configureEach {
        it.options.encoding = "UTF-8"
        it.options.release = 25
    }
}