# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
mod_version = 1.3.1-26.2
maven_group = fr.gallonemilien
archives_name = dopedhorses
mod_name = dopedhorses
enabled_platforms = fabric,neoforge

# Minecraft properties
minecraft_version = 26.2
pack_format_number = 18


# Dependencies
architectury_api_version = 21.0.2
fabric_loader_version = 0.18.5
fabric_api_version = 0.154.0+26.2
neoforge_version = 26.2.0.7-beta
midnightlib_version_fabric=1.9.3+26.2-fabric
midnightlib_version_neoforge=1.9.3+26.2-neoforge