# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
mod_version = 1.2.4-26.1
maven_group = fr.gallonemilien
archives_name = dopedhorses
mod_name = dopedhorses
enabled_platforms = fabric,neoforge

# Minecraft properties
minecraft_version = 26.1.2
pack_format_number = 18


# Dependencies
architectury_api_version = 20.0.5
fabric_loader_version = 0.18.5
fabric_api_version = 0.144.3+26.1
neoforge_version = 26.1.2.73
midnightlib_version_fabric=1.9.3+26.1-fabric
midnightlib_version_neoforge=1.9.3+26.1-neoforge