modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "CC0-1.0"

[[mods]]
modId = "dopedhorses"
version = "${version}"
displayName = "DopedHorses"
authors = "GallonEmilien"
description = '''
A mod that add doped horses ! Horses speed now depends on the block they are walking on and if they are wearing some shoes
'''
#logoFile = ""

[[dependencies.dopedhorses]]
modId = "neoforge"
type = "required"
versionRange = "[21.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.dopedhorses]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.dopedhorses]]
modId = "architectury"
type = "required"
versionRange = "[15.0.1,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "dopedhorses.mixins.json"
